/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type FileType = "ecg" | "imaging" | "lab_result" | "medical_report" | "other" | "prescription";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type RecordStatus = "completed" | "pending";

export type RecordType = "post_anesthesia" | "pre_anesthesia";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Account {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Timestamp;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Timestamp;
  userId: string;
}

export interface Consent {
  consent_text: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  ip_address: string | null;
  is_accepted: boolean;
  patient_age: number | null;
  patient_id_number: string;
  patient_name: string;
  patient_phone: string | null;
  record_id: string;
  signature_data: string | null;
  signed_at: Timestamp | null;
  user_agent: string | null;
}

export interface DoctorEvaluation {
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  doctor_id: string;
  evaluation_data: Generated<Json | null>;
  id: Generated<string>;
  is_complete: Generated<boolean>;
  is_draft: Generated<boolean>;
  record_id: string;
  updated_at: Generated<Timestamp>;
}

export interface Patient {
  created_at: Generated<Timestamp>;
  date_of_birth: Timestamp | null;
  email: string | null;
  first_name: string;
  id: Generated<string>;
  identification_number: string;
  last_name: string;
  phone: string | null;
  updated_at: Generated<Timestamp>;
}

export interface PatientFile {
  deleted_at: Timestamp | null;
  description: string | null;
  file_name: string;
  file_size: number;
  file_type: FileType;
  id: Generated<string>;
  is_deleted: Generated<boolean>;
  mime_type: string;
  patient_id: string;
  record_id: string | null;
  storage_path: string;
  storage_url: string | null;
  uploaded_at: Generated<Timestamp>;
  uploaded_by: string | null;
}

export interface PatientMedicalProfile {
  allergies: Generated<Json | null>;
  created_at: Generated<Timestamp>;
  family_history: Generated<Json | null>;
  id: Generated<string>;
  is_current: Generated<boolean>;
  lifestyle: Generated<Json | null>;
  medical_history: Generated<Json | null>;
  medications: Generated<Json | null>;
  patient_id: string;
  surgical_history: Generated<Json | null>;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface PatientRecordForm {
  completed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  ip_address: string | null;
  is_draft: Generated<boolean>;
  record_id: string;
  record_specific_answers: Generated<Json | null>;
  updated_at: Generated<Timestamp>;
  used_medical_profile_version: number | null;
  user_agent: string | null;
}

export interface Record {
  assigned_doctor_id: string | null;
  created_at: Generated<Timestamp>;
  created_by: string;
  form_link_token: string;
  id: Generated<string>;
  notes: string | null;
  patient_id: string;
  record_number: string;
  scheduled_date: Timestamp | null;
  status: Generated<RecordStatus>;
  type: RecordType;
  updated_at: Generated<Timestamp>;
}

export interface Session {
  createdAt: Timestamp;
  expiresAt: Timestamp;
  id: string;
  ipAddress: string | null;
  token: string;
  updatedAt: Timestamp;
  userAgent: string | null;
  userId: string;
}

export interface User {
  createdAt: Timestamp;
  email: string;
  emailVerified: number;
  id: string;
  image: string | null;
  name: string;
  updatedAt: Timestamp;
}

export interface UserRole {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  role: string;
  user_id: string;
}

export interface Verification {
  createdAt: Timestamp;
  expiresAt: Timestamp;
  id: string;
  identifier: string;
  updatedAt: Timestamp;
  value: string;
}

export interface DB {
  account: Account;
  consent: Consent;
  doctor_evaluation: DoctorEvaluation;
  patient: Patient;
  patient_file: PatientFile;
  patient_medical_profile: PatientMedicalProfile;
  patient_record_form: PatientRecordForm;
  record: Record;
  session: Session;
  user: User;
  user_role: UserRole;
  verification: Verification;
}
